image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine

stages:
  - build
  - lint
  - test

cache:
  paths:
    - vendor/

build:
  stage: build
  script:
    - composer install
  artifacts:
    expire_in: 1 week
    paths:
      - vendor/
  tags:
    - staging

lint:
  stage: lint
  script:
    - ./vendor/bin/parallel-lint -j 4 --blame src
    - ./vendor/bin/parallel-lint -j 4 --blame tests
  tags:
    - staging

test:
  stage: test
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml
  tags:
    - staging
